new TradingView.MediumWidget({
  symbols: [
    ["Total", "CRYPTOCAP:TOTAL|12M"],
    ["Total 2 (-btc)", "CRYPTOCAP:TOTAL2|12M"],
    ["Total 3 (-btc&eth)", "CRYPTOCAP:TOTAL3|12M"],
    ["Total DEFI", "CRYPTOCAP:TOTALDEFI|12M"],
    ["Total Others", "CRYPTOCAP:OTHERS|12M"],
    ["BTC", "BITSTAMP:BTCUSD|12M"],
    ["ETH", "BITSTAMP:ETHUSD|12M"],
    ["XMR", "KRAKEN:XMRUSD|12M"],
    ["Nasdaq", "CURRENCYCOM:US100|12M"],
    ["Sp500", "CURRENCYCOM:US500|12M"],
    ["DOW", "CURRENCYCOM:US30|12M"],
    ["GOLD", "FOREXCOM:XAUUSD|12M"],
    ["SILVER", "FOREXCOM:XAGUSD|12M"],
    ["DXY", "CAPITALCOM:DXY|12M"],
  ],
  chartOnly: false,
  width: "100%",
  height: "100%",
  locale: "es",
  colorTheme: "dark",
  isTransparent: true,
  autosize: true,
  showVolume: true,
  hideDateRanges: false,
  scalePosition: "right",
  scaleMode: "Logarithmic",
  fontFamily: "Trebuchet MS, sans-serif",
  noTimeScale: false,
  valuesTracking: "2",
  chartType: "candlesticks",
  fontColor: "rgba(238, 238, 238, 1)",
  gridLineColor: "rgba(240, 243, 250, 0.06)",
  upColor: "#22ab94",
  downColor: "#4A1692",
  borderUpColor: "#22ab94",
  borderDownColor: "#4A1692",
  wickUpColor: "#22ab94",
  wickDownColor: "#4A1692",
  container_id: "tradingview_c5fa1",
});
